### ISSUE TITLE
Allow more granular configuration overrides

### ISSUE THREAD

**Issue by m1foley** [m1foley/fit-commit#12]
This `.pre_commit.yml` should work:

```yaml
---
Validators/LineLength:
  SummaryWarnLength: 72
```

That currently leads to an error because it expects `Enabled` to be specified again. Config properties should be merged more intelligently.
